version: 2.1
orbs:
  architect: giantswarm/architect@2.4.1

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "node-exporter-app"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/integration-test:
          context: architect
          name: basic-integration-test
          install-app-platform: true
          test-dir: "integration/test/basic"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-to-default-app-catalog

      - architect/integration-test:
          name: "upgrade-integration-test"
          install-app-platform: true
          test-dir: "integration/test/upgrade"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-to-default-app-catalog

      - architect/push-to-app-catalog:
          context: architect
          name: push-node-exporter-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "node-exporter-app"
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-node-exporter-to-shared-app-collection
          app_name: "node-exporter-app"
          app_namespace: "monitoring"
          app_collection_repo: "shared-app-collection"
          requires:
            - push-node-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-node-exporter-to-aws-app-collection
          app_name: "node-exporter-app"
          app_namespace: "monitoring"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-node-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-node-exporter-to-azure-app-collection
          app_name: "node-exporter-app"
          app_namespace: "monitoring"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-node-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-node-exporter-to-kvm-app-collection
          app_name: "node-exporter-app"
          app_namespace: "monitoring"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-node-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
              
      - architect/push-to-app-collection:
          context: architect
          name: push-node-exporter-to-vmware-app-collection
          app_name: "node-exporter-app"
          app_namespace: "monitoring"
          app_collection_repo: "vmware-app-collection"
          requires:
            - push-node-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
